### ISSUE TITLE
Color variation control

### ISSUE THREAD

**Issue by ivanmotta** [staffantan/unityglitch#4]
Hi there! First of all, thank you very much for the script! It's a beautiful effect.
Second, I'm not a experienced programmer, and in my game i can't change colors for a long time, they are too important for player orientation. But I can't understand the values that control how often you change then, or for how long. Is there a way expose this amount? Thank you!

**Comment by StaffanWidegarnAhlvik** [comment]
Adding control sliders to the separate effects.

**Comment by ivanmotta** [comment]
Man, I just love you! Thank you very much!
Will credit it and send you the game when ready. I'm @nonsensebull
